### ISSUE TITLE
purrr or other required?

### ISSUE THREAD

**Issue by macartan** [gerasy1987/hiddenmeta#1]
> hpop_estimands(df)
 Error: Problem with `mutate()` input `degree`.
x could not find function "map_int"
i Input `degree` is `map_int(links, ~length(.x))`.
Run `rlang::last_error()` to see where the error occurred.

**Comment by gerasy1987** [comment]
Yes `purrr::map_int()` was not imported properly, sorry. I think this should be addressed now
