### ISSUE TITLE
Inverse wave weighting for sampling in sample_rds()

### ISSUE THREAD

**Issue by gerasy1987** [gerasy1987/hiddenmeta#5]
I realized that we already have weights implemented when drawing from the pool of eligible nodes in RDS. The weighting is currently done according to the inverse of the wave (i.e. those who were sampled from network closer to initial seed are more likely to be drawn):
```
new <- dplyr::slice_sample(eligible, n = 1, replace = FALSE, weight_by = 1/wave)
```

Do we want to change this?

**Comment by macartan** [comment]
Are there unconditional weights? E.g. before a seed is drawn could we
assess the probability some one enters the sample (surely yes via
simulation at least )

**Comment by gerasy1987** [comment]
@macartan, yes, since everyone is drawn as a seed with equal probability and since probability of establishing a link within hidden population is also given we can definitely get the probability of someone entering the sample upfront.
