### ISSUE TITLE
Shiny app for input of parameters

### ISSUE THREAD

**Issue by gerasy1987** [gerasy1987/hiddenmeta#8]
It would be useful if we can create a Shiny app that will collect and merge the parameters of different studies and later probably also allow for analysis of those

**Comment by macartan** [comment]
Would a google form do the same work?

**Comment by gerasy1987** [comment]
yes, but my thinking was that this could also take various priors on each study population beyond the study characteristics provided by the teams. This is not urgent and maybe instead we can just upload the google form data on study characteristics as data.frame to such Shiny app.

**Comment by gerasy1987** [comment]
The idea is to switch to google form handler, so closing this
