### ISSUE TITLE
add missing study level estimators

### ISSUE THREAD

**Issue by gerasy1987** [gerasy1987/hiddenmeta#9]
Missing estimators are:

- [ ] GNSUM
- [x] Mark-recapture
- [x] Vincent Link-Tracing

**Comment by gerasy1987** [comment]
@till-tietz here are some things we need to do for the link-tracing method:

- [ ] Read the paper by Thompson and Vincent (there are two versions on nextcloud, my sense is that we only need the latest paper since both papers talk about the same method, but this needs to be verified if what they call snowball sampling in 2020 draft is the same as link-tracing in 2016 draft)
- [ ] Summarize the method, both the sampling and how they do estimation (very broad strokes, no proofs or too many details), and prepare that summary to be added to Methods summary on package website. Might be particularly useful to note the differences in sampling compared to standard RDS and why those differences are crucial
- [ ] Go through simulations code and find info relevant for implementing the method in `hiddenmeta`, namely:
   - [ ] FInd out (and describe in the summary as well) the sampling data required for estimation
   - [ ] Find out how they calculate uncertainty (if through bootstrap, parametric estimation, or Bayesian estimation). If they rely on bootstrap we might be able to use the existing RDS bootstrap implemented in the package
   - [ ] Find out how they calculate the estimator (if the uncertainty is calculated based on bootstrap that's all we need to calculate point estimates and SEs)
- [ ] Finally, implement the estimator in the package

**Comment by till-tietz** [comment]
link-tracing is implemented and fully functional
